import {base} from "next/dist/build/webpack/config/blocks/base";


// components/RootLayout.js
import { UserProvider } from "@/app/UserProvider";
import Link from 'next/link';


const Navbar = () => {
    return (
        <nav className="bg-gray-800 p-4 text-white">
            <div className="container mx-auto flex items-center justify-between">
                <div className="text-white text-xl font-bold">
                    <Link href={'/'}>Todo App</Link>
                </div>
                <div className="space-x-4">
                    <Link href={'/register'}>register</Link>
                    <Link href={'/signin'}>signin</Link>
                    <Link href={'/logout'}>logout</Link>
                </div>
            </div>
        </nav>
    );
};


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body>
        <UserProvider>
            <Navbar/>
            <div className="container mx-auto p-4">{children}</div>
        </UserProvider>
        </body>
        </html>
    );
}
